### ISSUE TITLE
Smalltalk use

### ISSUE THREAD

**Issue by Ducasse** [rko281/ReStoreForPharo#1]
Hi 

I was browsing the code and in Pharo 

Smalltalk at: 

is better turned in 

self class or self environment at:

It will ease future evolution. 
S.

**Comment by rko281** [comment]
Hi - thanks for the advice.

At the moment the core ReStore code is a straight port from Dolphin; as things progress I’ll be making things more dialect agnostic/Pharo-friendly.

Cheers,

John

**Comment by rko281** [comment]
Addressed with 20352d7c469d751941f7c594a05166f58f71bdac
