### ISSUE TITLE
select:thenCollect:

### ISSUE THREAD

**Issue by akevalion** [rko281/ReStoreForPharo#15]
Hello I have a big table with 30 fields

I do not want to return all the fields with select operation.
I want only to use 3 fields
Then I wan to use 
```st
Match storedInstances select:[:match | match home_id = my_home_id  ] 
thenCollect: [:match | {match home_id. match away_id. match date } ]
```

I got this error
<img width="997" alt="image" src="https://user-images.githubusercontent.com/10532890/174031998-e43257ed-9be3-495a-8cdb-90bfd0a64747.png">

How can I collect only the interesting fields

**Comment by rko281** [comment]
Hi - the way to do this is using the `||` operator to combine the fields, e.g.

```smalltalk
Match storedInstances select:[:match | match home_id = my_home_id  ] 
thenCollect: [:match | match home_id || match away_id || match date ]
```

Please let me know if this works for you.

**Comment by akevalion** [comment]
It works!
