### ISSUE TITLE
SSWDBInstancesCollection with `select distinct`

### ISSUE THREAD

**Issue by akevalion** [rko281/ReStoreForPharo#16]
Is it possible to have select distinct?

https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_distinct

**Comment by rko281** [comment]
Try using `project:`instead of `collect:`. 

Example (using the `SSW ReStore Examples` classes):
```smalltalk
"Includes duplicates"
CustomerOrder storedInstances collect: [ :each | each customer].

"No duplicates"
CustomerOrder storedInstances project: [ :each | each customer].
```

**Comment by akevalion** [comment]
It works perfect!
