### ISSUE TITLE
Error loading restore for pharo TypeConverters

### ISSUE THREAD

**Issue by akevalion** [rko281/ReStoreForPharo#25]
<img width="880" alt="image" src="https://github.com/rko281/ReStoreForPharo/assets/10532890/9af93295-04db-4217-adac-7fbf0c635e77">

**Comment by akevalion** [comment]
In pharo 12

**Comment by rko281** [comment]
This is an issue with the Pharo-MySQL repository; I've submitted a [fix](https://github.com/pharo-rdbms/Pharo-MySQL/pull/20) for this but it's still pending approval.

If you click Return in the debugger and hit OK the load should proceed and be successful (MySQL will still work).
