### ISSUE TITLE
Hangs Pharo 8 Image wit P3 Running Examples

### ISSUE THREAD

**Issue by tblanchard** [rko281/ReStoreForPharo#3]
I thought I might give this a try and loaded it up.

Attempting to run the examples, the image locks up trying to create the tables.  I do not understand why.  But I have to kill the process externally, cmd-. does not work.

Using P3 to PostgreSQL

**Comment by rko281** [comment]
ReStore is currently only tested with Pharo 7.

I've just tested a fresh Pharo 7 image and verified everything works correctly with P3 to PostgreSQL, but I can confirm the issue you're seeing with Pharo 8.

I'll take a deeper look at Pharo 8 when I have some time.

**Comment by rko281** [comment]
Fixed with commit https://github.com/rko281/ReStoreForPharo/commit/a87ee0a2cb7855e892ef09de20da2624e233d3a9

ReStore should now work on both Pharo 7 and Pharo 8 - all SUnits pass; examples work as described.
