### ISSUE TITLE
query in Dictionary

### ISSUE THREAD

**Issue by datensenke** [rko281/ReStoreForPharo#6]
If I have a setup like:
`
reStoreDefinition
	^ super reStoreDefinition
		define: #name as: (String maxSize: 4096);
		define: #dict
			as: (Dictionary of: (String maxSize: 50)->(String maxSize: 50))
`
how do I do a query on the #dict?
I was thinking something like
`
Data storedInstances select: [:each| each dict includes: {key1->value1.key2->value2}].
`

**Comment by rko281** [comment]
ReStore's querying generally tries to use standard collection methods, so this would need to be:
```
Data storedInstances select: 
[:each| 
(each dict includesAssociation: key1->value1) 
& (each dict includesAssociation: key2->value2)].
```

...however ReStore doesn't currently support `includesAsssociation:`. I'll add this.
