### ISSUE TITLE
link table ID column types are (only) integer though the source / target table IDs may be other types

### ISSUE THREAD

**Issue by sanjayminni** [rko281/ReStoreForPharo#8]
The columns created in link tables that store the values of PKs of source and target tables are of type integer whereas the PK types may be some other type (UUID in my case
![ReStoreLinkTable](https://user-images.githubusercontent.com/12030766/143017260-aa79b9c8-2978-4ede-a8d4-b9f73dd10c22.jpg)

**Comment by rko281** [comment]
I can confirm this issue, specifically the `source_id` field is always created as `Integer` type. I'll submit a fix for this with additional tests to verify.

The `target_id` field should already be created with the corresponding type of the target class's ID class; correct behaviour under this scenario is tested by `SSWReStoreAlternativeIDTest>>testForeignIDCollection`. 

Note that ReStore does not check for changes in field types, so if you change the type of a field (either via a declaration in `reStoreDefinition` or by changing a class's ID class) you need to either drop and recreate the table, or manually change the field type in the database. This is a long-standing "to do" for ReStore, the main issue being how to sensibly handle type changes in already-populated tables (coerce values to the new type? null all rows? provide a manual migration strategy?).

**Comment by sanjayminni** [comment]
yes target ids class seems to be correctly interpreted.

changing a field type can be a complex task and I am fine to do so at the database manually - hopefully there will be no sync problems in class changes to database or even a tool to compare the database types with the class types and show the difference is fine  

I notice a problem that surfaces like this on synchroniseAllClasses:
#Error P3Error PostgreSQL bind message supplies 3 parameters, but prepared statement "2" requires 1
it seems this happens when i do 
  ReStore destroyAllClasses .
  ReStore resetClasses .
  ReStore addClass: ...
  ReStore synchronizeAllClasses
(I am doing this frequently in my design phase)
after that i am unable to synchronize / create the tables in any way 
then it works fine once i do 
ReStore disconnect

**Comment by rko281** [comment]
Could you raise the error as a new issue, ideally with a stack trace?
